apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-11-06T12:21:32Z","name":"banndcampapi","namespace":"default","resourceVersion":"27758","uid":"c35dca0c-a9df-4aff-9b2f-da33ed44bd64"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.104.13.85","clusterIPs":["10.104.13.85"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30794,"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"bandcampapi"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"hostname":"localhost"}]}}}
  creationTimestamp: "2025-11-06T12:22:04Z"
  name: banndcampapi
  namespace: default
  resourceVersion: "27816"
  uid: aaa636fb-1256-470e-99ce-ce38843869e3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.13.85
  clusterIPs:
  - 10.104.13.85
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30794
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: bandcampapi
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
